#cloud-config

hostname: ho-srvt-node03

coreos:
  units:
    - name: systemd-timesyncd.service
      command: stop
      mask: true
    - name: ntpd.service
      command: start
      enable: true
    - name: systemd-networkd.service
      command: stop
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=ens32

        [Network]
        DNS=10.1.1.20
        Address=10.1.15.101/24
        Gateway=10.1.15.1
    - name: down-interfaces.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set ens32 down
        ExecStart=/usr/bin/ip addr flush dev ens32
    - name: systemd-networkd.service
      command: restart
users:
    - name: core
      passwd: "$6$SALT$Vla3k9Ain5XcINOWsIsD5XSiNqo/O92pL2jdAQgAwufoPdphkuw02G69cPsQnX/DTlgWGiA3TVnOqv6L/q4nR1"
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkGbU0h5MMsVCy3aDPOOTWvSNdKiXj1bKb5bhH8Z7yNo3UKksTMfoYzUxMOHtxXwnAR4m9xQ0GeLkdIz0bwpf81/NEX9vZwUSQ5QN+Mvp/RZkCMSCFRQD4eGe84JMGHDa6jdhngFDsB9oNbUOCTJoXxq93jNXYgtXxZVYJ5chRUa3tkVPBP0A4ByVnh5vrg10ypnVBHgWk5sg4RyQyBDUid1D3We/HdWry/Duo/WnSz6bOQfzcZqwfIO96IYvJMXW61vN+rKDfP44CnadrEeMYi2a0Fk004dNAGq57A+Vp/QDZM7cXmBWxIo9jB6n2UyHSjWcicfTCR/WqRCzRiWA5w=="
      groups:
        - "sudo"
        - "docker"
    - name: admin
      passwd: "$6$SALT$Vla3k9Ain5XcINOWsIsD5XSiNqo/O92pL2jdAQgAwufoPdphkuw02G69cPsQnX/DTlgWGiA3TVnOqv6L/q4nR1"
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkGbU0h5MMsVCy3aDPOOTWvSNdKiXj1bKb5bhH8Z7yNo3UKksTMfoYzUxMOHtxXwnAR4m9xQ0GeLkdIz0bwpf81/NEX9vZwUSQ5QN+Mvp/RZkCMSCFRQD4eGe84JMGHDa6jdhngFDsB9oNbUOCTJoXxq93jNXYgtXxZVYJ5chRUa3tkVPBP0A4ByVnh5vrg10ypnVBHgWk5sg4RyQyBDUid1D3We/HdWry/Duo/WnSz6bOQfzcZqwfIO96IYvJMXW61vN+rKDfP44CnadrEeMYi2a0Fk004dNAGq57A+Vp/QDZM7cXmBWxIo9jB6n2UyHSjWcicfTCR/WqRCzRiWA5w=="
            groups:
        - "sudo"
        - "docker"
write_files:
  - path: /etc/ntp.conf
    content: |
      server 0.10.1.1.20
      server 1.10.1.1.21
      # - Allow only time queries, at a limited rate.
      # - Allow all local queries (IPv4, IPv6)
      restrict default nomodify nopeer noquery limited kod
      restrict 127.0.0.1
      restrict [::1]
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: "root"
    content: |
      nameserver 10.1.1.20
  - path: /etc/profile.d/aliases.sh
    content: |
    alias l='ls -lFh'
    alias ll='ls -lFhA'
